#!/bin/bash
# Write build information into build-info.phtml template
buildInfoFile=adminhtml/template/config/build-info.phtml
git show -s --format="Build version: %H<BR>%nBuild date:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;%cd" --date=short >> $buildInfoFile

